"""Added Audit logs table

Revision ID: f08da71fa636
Revises: 41c26891a7e0
Create Date: 2023-04-17 19:15:03.767879

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f08da71fa636'
down_revision = '41c26891a7e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('public_id', sa.String(), nullable=False),
                    sa.Column('actor', sa.String(length=255), nullable=False),
                    sa.Column('event', sa.String(length=255), nullable=False),
                    sa.Column('outcome', sa.String(
                        length=255), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('ip_address', sa.String(
                        length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('public_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
